version: '3'

services:
    db:
        image: postgres
        environment:
          POSTGRES_DB: "db"
          POSTGRES_HOST_AUTH_METHOD: "trust"

    web:
        build: ./djangochat
        volumes:
            - ./djangochat:/usr/src/app/
        ports:
            - "8000:8000"