version: '3'

services:
    # db:
    #     image: postgres:15-alpine
    #     environment:
    #       POSTGRES_DB: "db"
    #       POSTGRES_HOST_AUTH_METHOD: "trust"

    web:
        build: 
            context: ./djangochat
            dockerfile: Dockerfile

        volumes:
            - ./djangochat:/usr/src/app/djangochat
        ports:
            - "8000:8000"
        # depends_on:
        #     - db
    
    frontend:
        build: 
            context: ./frontend
            dockerfile: Dockerfile
        
        volumes:
            - ./frontend:/usr/src/app/frontend
        ports:
            - "3000:3000"    

        depends_on:
            - web
            